CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
    ('1','HOZAIFA','ISLAMABAD','******',14),
    ('2','ESHAN','RAWALPNDI','******',13),
    ('3','FAHEEM','CHAKWAL','******',17),
    ('4','MATEEN','HYDRABAD','******',15),
    ('5','SARIM','KARACHI','******',16),
    ('6','ZEESHAN','PESHAWAR','******',18);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE=18 AND ADDRESS='PESHAWAR';
SELECT * FROM STUDENT WHERE AGE=17  OR NAME='FAHEEM';
SELECT * FROM STUDENT WHERE AGE=13 AND (NAME='ESHAN' OR NAME='SARIM');
SELECT MIN(AGE) AS MINIMUM_AGE FROM STUDENT;
SELECT MAX(AGE) AS MAXIMUM_AGE FROM STUDENT;